// eslint-config-next@16 ships its "core-web-vitals" and "next/typescript"
// presets as native ESLint 9 flat-config arrays (Linter.Config[]) — see
// node_modules/eslint-config-next/dist/*.d.ts. FlatCompat (@eslint/eslintrc)
// exists to translate LEGACY eslintrc-shaped shareable configs into flat
// config; feeding it something that is already flat sends the flat-config
// plugin objects (eslint-plugin-react's preset self-references itself at
// configs.recommended.plugins.react) through the legacy ajv schema
// validator, which fails and then crashes trying to JSON.stringify the
// circular plugin object for its error message ("Converting circular
// structure to JSON"). Importing the flat presets directly avoids the
// legacy translation path entirely.
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

const eslintConfig = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "coverage/**",
      "next-env.d.ts",
      "playwright-report/**",
      "test-results/**",
      // Generated by postbuild (scripts/build-sw.mjs) from app/sw.ts —
      // gitignored (see .gitignore), not source. Left un-ignored here it
      // gets linted like hand-written code the moment anyone runs a local
      // build before `pnpm lint`.
      "public/sw.js",
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypescript,
];

export default eslintConfig;
